
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "asgard-deploykf"
  namespace: "argocd"
  labels:
    app.kubernetes.io/name: asgard-deploykf
    app.kubernetes.io/component: deploykf
    app.kubernetes.io/part-of: "asgard-deploykf"
spec:
  project: "default"
  source:
    repoURL: "https://github.com/baseonballs/bifrost-gitops.git"
    targetRevision: "main"
    path: "asgard-deploykf/v0.1.1/argocd"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"