apiVersion: v1
kind: Namespace
metadata:
  name: "bifrost"
  labels:
    app.kubernetes.io/component: bifrost
    app.kubernetes.io/part-of: bifrost
    istio-injection: disabled
    bifrost.asgard.baseonballs.io/rev: v0.0.1