
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "bifrost-realms"
  namespace: "argocd"
  labels:
    app.kubernetes.io/name: bifrost-realms
    app.kubernetes.io/part-of: bifrost
spec:
  project: "default"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
  source:
    repoURL: "https://github.com/baseonballs/jdev-asgard-gitops.git"
    targetRevision: "main"
    path: "asgard-bifrost-realms/v0.0.1/cluster-wide"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"