
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dkf-core--deploykf-istio-gateway
  namespace: "argocd"
  labels:
    app.kubernetes.io/name: deploykf-istio-gateway
    app.kubernetes.io/component: deploykf-core
    app.kubernetes.io/part-of: "deploykf"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
  source:
    repoURL: "https://github.com/baseonballs/jdev-asgard-mlops"
    targetRevision: "main"
    path: "deploykf_0.1.1/manifests/deploykf-core/deploykf-istio-gateway"
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values-overrides.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "deploykf-istio-gateway"
