
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kf-tools--notebooks--notebook-controller
  namespace: "argocd"
  labels:
    app.kubernetes.io/name: notebook-controller
    app.kubernetes.io/component: kubeflow-tools
    app.kubernetes.io/part-of: "deploykf"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "default"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      ## ensure argo-cd does not remove the fields added by kyverno
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
  source:
    repoURL: "https://github.com/baseonballs/jdev-asgard-gitops.git"
    targetRevision: "main"
    path: "deploykf/v0.1.1/manifests/kubeflow-tools/notebooks/notebook-controller"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeflow
  ignoreDifferences:
    ## `rules` are aggregated when `aggregationRule.clusterRoleSelectors` is set
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jqPathExpressions:
        - "select(.aggregationRule.clusterRoleSelectors | length > 0) | .rules"