
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kf-tools--pipelines
  namespace: "argocd"
  labels:
    app.kubernetes.io/name: pipelines
    app.kubernetes.io/component: kubeflow-tools
    app.kubernetes.io/part-of: "deploykf"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "default"
  source:
    repoURL: "https://github.com/baseonballs/jdev-asgard-gitops.git"
    targetRevision: "main"
    path: "deploykf/v0.1.1/manifests/kubeflow-tools/pipelines"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      ## ensure argo-cd does not remove the fields added by kyverno
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
  ignoreDifferences:
    ## `caBundle` is injected by cert-manager
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - ".webhooks[]?.clientConfig.caBundle"

    ## `rules` are aggregated when `aggregationRule.clusterRoleSelectors` is set
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jqPathExpressions:
        - "select(.aggregationRule.clusterRoleSelectors | length > 0) | .rules"

    ## we use kyverno to trigger restarts by setting the "deploykf.org/restart-trigger" annotation when secrets change
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations/deploykf.org~1restart-trigger