
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kf-tools--volumes--volumes-web-app
  namespace: "argocd"
  labels:
    app.kubernetes.io/name: volumes-web-app
    app.kubernetes.io/component: kubeflow-tools
    app.kubernetes.io/part-of: "deploykf"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "default"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      ## ensure argo-cd does not remove the fields added by kyverno
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
  source:
    repoURL: "https://github.com/baseonballs/jdev-asgard-mlops.git"
    targetRevision: "main"
    path: "deploykf/v0.1.1/manifests/kubeflow-tools/volumes/volumes-web-app"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeflow
