
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dkf-dep--istio
  namespace: "argocd"
  labels:
    app.kubernetes.io/name: istio
    app.kubernetes.io/component: deploykf-dependencies
    app.kubernetes.io/part-of: "deploykf"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "default"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
  source:
    repoURL: "https://github.com/baseonballs/jdev-asgard-mlops.git"
    targetRevision: "main"
    path: "deploykf/v0.1.1/manifests/deploykf-dependencies/istio"
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values-overrides.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "istio-system"
  ignoreDifferences:
    ## istio patches the `failurePolicy` from "Ignore" to "Fail" once the webhook is up
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jqPathExpressions:
        - ".webhooks[]?.failurePolicy"